#!/usr/bin/env bash
#
# Generates the compose file and the load-balancer config for one arm.
#
# The instance count is a PARAMETER, not a hard-coded assumption: the whole experiment is a
# comparison of 1 instance against 2 (and later N), so the topology is emitted from INSTANCES
# rather than kept as two hand-maintained compose files that could drift apart.
#
# Inputs (environment):
#   ARM        arm label, used only for naming the run             (default: arm0)
#   INSTANCES  number of app instances behind the balancer         (default: 1)
#   STORE      memory | redis — which authorization-code store     (default: memory)
#   APP_CPUS   CPU budget PER instance                             (default: 2)
#   APP_MEM    memory limit per instance                           (default: 1g)
#   HEAP       -Xmx for each instance                              (default: 512m)
#   MASTER_KEY base64 32-byte signing master key (required)
#   RATELIMIT  off | default | high                                (default: high)
#   OUT_DIR    where to write the generated files                  (default: perf/.run)
#
set -euo pipefail

ARM="${ARM:-arm0}"
INSTANCES="${INSTANCES:-1}"
STORE="${STORE:-memory}"
APP_CPUS="${APP_CPUS:-2}"
APP_MEM="${APP_MEM:-1g}"
HEAP="${HEAP:-512m}"
RATELIMIT="${RATELIMIT:-high}"
PG_PASSWORD="${PG_PASSWORD:-perf-local-only}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERF_DIR="$(dirname "$HERE")"
REPO_ROOT="$(dirname "$PERF_DIR")"
OUT_DIR="${OUT_DIR:-$PERF_DIR/.run}"

if [[ -z "${MASTER_KEY:-}" ]]; then
  echo "gen-topology: MASTER_KEY is required (base64 of 32 random bytes)" >&2
  exit 2
fi
if [[ "$INSTANCES" -lt 1 ]]; then
  echo "gen-topology: INSTANCES must be >= 1" >&2
  exit 2
fi

mkdir -p "$OUT_DIR"

# --- rate limiting ------------------------------------------------------------------------
# The shipped default is 20 token requests and 60 authorize requests per minute per
# (tenant, client_id). That is FAR below any interesting load, so with the default settings
# the measured ceiling would be the rate limiter's configuration and nothing else. The load
# arms therefore run with the limiter raised well clear of the offered rate, and the run
# manifest records which setting was used so the number is never read as unqualified.
case "$RATELIMIT" in
  off)     RL_ENABLED=false; RL_TOKEN=20;     RL_AUTHORIZE=60 ;;
  default) RL_ENABLED=true;  RL_TOKEN=20;     RL_AUTHORIZE=60 ;;
  high)    RL_ENABLED=true;  RL_TOKEN=1000000; RL_AUTHORIZE=1000000 ;;
  *) echo "gen-topology: RATELIMIT must be off|default|high" >&2; exit 2 ;;
esac

# --- nginx: plain round-robin over the instances -------------------------------------------
{
  echo "# Generated by gen-topology.sh — arm=$ARM instances=$INSTANCES store=$STORE"
  echo "events { worker_connections 4096; }"
  echo "http {"
  echo "  access_log off;"
  echo "  upstream tessera {"
  for i in $(seq 1 "$INSTANCES"); do
    echo "    server app$i:8090;"
  done
  # Keepalive to the upstream: without it every login pays two fresh TCP handshakes to the
  # app and the measurement drifts towards connection setup rather than the login flow.
  echo "    keepalive 256;"
  echo "  }"
  echo "  server {"
  echo "    listen 8080;"
  echo "    location / {"
  echo "      proxy_pass http://tessera;"
  echo "      proxy_http_version 1.1;"
  echo "      proxy_set_header Connection \"\";"
  echo "      proxy_set_header Host \$host;"
  # Never follow the 302 — the authorization response IS the redirect, and the driver has
  # to read the code out of the Location header itself.
  echo "      proxy_redirect off;"
  echo "    }"
  echo "  }"
  echo "}"
} > "$OUT_DIR/nginx.conf"

# --- compose --------------------------------------------------------------------------------
COMPOSE="$OUT_DIR/compose.yaml"
{
  echo "# Generated by gen-topology.sh — DO NOT EDIT (regenerate instead)."
  echo "# arm=$ARM instances=$INSTANCES store=$STORE cpus/instance=$APP_CPUS heap=$HEAP ratelimit=$RATELIMIT"
  echo "name: tessera-perf"
  echo ""
  echo "services:"
  echo "  postgres:"
  echo "    image: postgres:17-alpine"
  echo "    environment:"
  echo "      POSTGRES_DB: tessera"
  echo "      POSTGRES_USER: tessera"
  echo "      POSTGRES_PASSWORD: $PG_PASSWORD"
  echo "    command: [\"postgres\", \"-c\", \"max_connections=300\"]"
  echo "    healthcheck:"
  echo "      test: [\"CMD-SHELL\", \"pg_isready -U tessera -d tessera\"]"
  echo "      interval: 2s"
  echo "      timeout: 3s"
  echo "      retries: 30"
  echo "    tmpfs:"
  # The database is a fixture, not the subject: keeping it on tmpfs removes host disk
  # behaviour (and APFS fsync latency) from a measurement that is about the login flow.
  echo "      - /var/lib/postgresql/data"
  echo ""

  if [[ "$STORE" == "redis" ]]; then
    echo "  redis:"
    echo "    image: redis:7-alpine"
    echo "    command: [\"redis-server\", \"--save\", \"\", \"--appendonly\", \"no\"]"
    echo "    healthcheck:"
    echo "      test: [\"CMD\", \"redis-cli\", \"ping\"]"
    echo "      interval: 2s"
    echo "      timeout: 3s"
    echo "      retries: 30"
    echo ""
  fi

  for i in $(seq 1 "$INSTANCES"); do
    port=$((8090 + i))
    echo "  app$i:"
    echo "    image: tessera-perf:local"
    echo "    build:"
    echo "      context: $REPO_ROOT"
    echo "      dockerfile: perf/docker/Dockerfile.jvm"
    echo "    depends_on:"
    echo "      postgres:"
    echo "        condition: service_healthy"
    if [[ "$STORE" == "redis" ]]; then
      echo "      redis:"
      echo "        condition: service_healthy"
    fi
    echo "    environment:"
    echo "      JAVA_OPTS: \"-Xms$HEAP -Xmx$HEAP -XX:+UseG1GC\""
    # %prod redirects plain HTTP to HTTPS. Without this override every single request in
    # the run would be answered with a 301 and nothing would be measured at all.
    echo "      QUARKUS_HTTP_INSECURE_REQUESTS: enabled"
    echo "      QUARKUS_HTTP_PORT: \"8090\""
    echo "      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres:5432/tessera"
    echo "      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/tessera"
    echo "      QUARKUS_DATASOURCE_USERNAME: tessera"
    echo "      QUARKUS_DATASOURCE_PASSWORD: $PG_PASSWORD"
    # A real (non-default) master key: the server refuses to boot outside dev/test on the
    # well-known development default. Generated per run, never committed.
    echo "      IAM_KEYS_MASTER_KEY: $MASTER_KEY"
    echo "      IAM_OIDC_ISSUER: http://localhost:8080"
    # The signing-key readiness gate is turned OFF for perf runs, and it is worth being
    # precise about why, because it is not a convenience.
    #
    # In a packaged production run that gate can never report UP: SigningKeyReadinessCheck
    # performs a BLOCKING await (UniAwait.atMost) from a health-check worker thread, and
    # Hibernate Reactive refuses that with "HR000068: This method should exclusively be
    # invoked from a Vert.x EventLoop thread". Independently of the thread problem, it also
    # counts ACTIVE keys for a hard-coded dev tenant only, so any other tenant reports DOWN
    # even when its own key is present and usable.
    #
    # Neither problem touches the signing path itself — the token endpoint signs from the
    # event loop and works — so the gate is disabled here and the harness instead gates on
    # liveness plus one real end-to-end login, which is a stronger readiness signal than the
    # probe was. Both defects are the application's, not the harness's, and are reported
    # rather than papered over.
    echo "      IAM_READINESS_SIGNING_KEY_ENABLED: \"false\""
    # Trusted-edge mode. SessionCookieFilter is default-closed: it STRIPS any caller-supplied
    # X-Subject-Id unless the deployment declares its ingress trustworthy, because trusting
    # that header without an edge that overwrites it is a complete authentication bypass —
    # any caller could assert someone else's subject with no credential at all.
    #
    # The harness is precisely the shape that flag describes: the balancer is the sole
    # ingress and the driver stands in for the authenticating proxy. Setting it here is what
    # lets the authorization exchange be driven at all. It is a PERF-ENVIRONMENT setting and
    # must never be copied into a deployment whose ingress does not strip the header.
    #
    # The consequence for the measurement is stated plainly in the README: this exercises the
    # AUTHORIZATION exchange, not end-user credential verification. A real login additionally
    # pays an Argon2id verification, which these numbers do not include.
    echo "      IAM_SUBJECT_TRUST_HEADER: \"true\""
    echo "      TESSERA_RATELIMIT_ENABLED: \"$RL_ENABLED\""
    echo "      TESSERA_RATELIMIT_TOKEN_CAPACITY: \"$RL_TOKEN\""
    echo "      TESSERA_RATELIMIT_TOKEN_REFILL: \"$RL_TOKEN\""
    echo "      TESSERA_RATELIMIT_AUTHORIZE_CAPACITY: \"$RL_AUTHORIZE\""
    echo "      TESSERA_RATELIMIT_AUTHORIZE_REFILL: \"$RL_AUTHORIZE\""
    if [[ "$STORE" == "redis" ]]; then
      # NOTE: the property that selects the Redis authorization-code store is owned by the
      # lane building that adapter (lane-redis-adapter) and is not on origin/main yet. Both
      # names below are passed through; whichever the adapter reads will bind, and the other
      # is inert. Reconcile to the real name once that adapter lands.
      echo "      TESSERA_AUTHCODE_STORE: redis"
      echo "      QUARKUS_REDIS_HOSTS: redis://redis:6379"
    fi
    echo "    ports:"
    # Every instance is ALSO addressable directly, not only through the balancer. The
    # cross-instance correctness check has to choose which instance issues and which
    # redeems; through a round-robin balancer that choice is not ours to make.
    echo "      - \"$port:8090\""
    echo "    deploy:"
    echo "      resources:"
    echo "        limits:"
    echo "          cpus: \"$APP_CPUS\""
    echo "          memory: $APP_MEM"
    echo ""
  done

  echo "  lb:"
  echo "    image: nginx:1.27-alpine"
  echo "    depends_on:"
  for i in $(seq 1 "$INSTANCES"); do
    echo "      - app$i"
  done
  echo "    volumes:"
  echo "      - $OUT_DIR/nginx.conf:/etc/nginx/nginx.conf:ro"
  echo "    ports:"
  echo "      - \"8080:8080\""
  echo ""

  echo "  k6:"
  echo "    image: grafana/k6:0.54.0"
  echo "    profiles: [\"driver\"]"
  echo "    depends_on:"
  echo "      - lb"
  echo "    volumes:"
  echo "      - $PERF_DIR/k6:/scripts:ro"
  echo "      - $OUT_DIR/results:/results"
  echo "    entrypoint: [\"k6\"]"
} > "$COMPOSE"

mkdir -p "$OUT_DIR/results"

echo "gen-topology: wrote $COMPOSE"
echo "gen-topology: wrote $OUT_DIR/nginx.conf"
echo "gen-topology: arm=$ARM instances=$INSTANCES store=$STORE cpus/instance=$APP_CPUS heap=$HEAP ratelimit=$RATELIMIT"
