//
// Emits the SQL that seeds one perf realm: a tenant-scoped ACTIVE Ed25519 signing key
// (with real envelope-encrypted private material) and one PUBLIC, PKCE-only OAuth client.
//
// Why a generator rather than a static .sql fixture: the private signing key is stored
// envelope-encrypted under a master key that is generated fresh per run (the server refuses
// to boot on the well-known dev default outside dev/test, and committing a real key to a
// public repository is not an option). The ciphertext therefore cannot be a checked-in
// constant — it has to be produced against the run's master key.
//
// Zero dependencies on purpose: it runs as a single-file source program on the JDK that is
// already required to build the project ("java SeedPerfRealm.java"), uses only javax.crypto
// and java.security, and writes SQL to stdout instead of opening a database connection —
// so it needs no JDBC driver and pipes straight into psql inside the Postgres container.
//
// The envelope format below MUST stay byte-compatible with
// tessera-persistence/.../crypto/EnvelopeCipher.java:
//   private_key_enc   = AES-256-GCM(DEK, nonce, PKCS#8 private key), 128-bit tag
//   private_key_nonce = the 12-byte GCM nonce for the above
//   dek_wrapped       = 12-byte wrap nonce || AES-256-GCM(masterKey, wrapNonce, DEK bytes)
//
// Usage:
//   java SeedPerfRealm.java --master-key <base64-32-bytes> [--tenant <uuid>] [--client-key <s>]
//                           [--redirect-uri <uri>] [--kid <s>] [--issuer <uri>]
//
import java.math.BigInteger;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.SecureRandom;
import java.security.interfaces.EdECPublicKey;
import java.util.Base64;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;

public final class SeedPerfRealm {

    private static final int GCM_TAG_BITS = 128;
    private static final int GCM_NONCE_BYTES = 12;
    private static final UUID ZERO_BASELINE = new UUID(0L, 0L);

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final HexFormat HEX = HexFormat.of();

    public static void main(String[] args) throws Exception {
        Map<String, String> opts = parseArgs(args);

        String masterKeyB64 = required(opts, "master-key");
        byte[] masterKey = Base64.getDecoder().decode(masterKeyB64);
        if (masterKey.length != 32) {
            throw new IllegalArgumentException(
                    "--master-key must decode to exactly 32 bytes; got " + masterKey.length);
        }

        UUID tenant = UUID.fromString(opts.getOrDefault("tenant", newTenant()));
        UUID clientRowId = UUID.randomUUID();
        UUID signingKeyRowId = UUID.randomUUID();
        String clientKey = opts.getOrDefault("client-key", "perf-client");
        String redirectUri = opts.getOrDefault("redirect-uri", "http://perf.invalid/callback");
        String kid = opts.getOrDefault("kid", "perf-key-1");
        String issuer = opts.getOrDefault("issuer", "http://localhost:8090");

        // --- signing key: fresh Ed25519 pair, private half envelope-encrypted -------------
        KeyPair pair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        byte[] pkcs8 = pair.getPrivate().getEncoded();
        String publicX = base64Url(rawPublicKey((EdECPublicKey) pair.getPublic()));

        SecretKey dek = newDek();
        byte[] nonce = randomNonce();
        byte[] ciphertext = gcm(Cipher.ENCRYPT_MODE, dek, nonce, pkcs8);
        byte[] wrappedDek = wrapDek(masterKey, dek);

        String publicJwk = "{\"kty\":\"OKP\",\"crv\":\"Ed25519\",\"use\":\"sig\","
                + "\"alg\":\"EdDSA\",\"kid\":\"" + kid + "\",\"x\":\"" + publicX + "\"}";

        // --- the SQL -----------------------------------------------------------------------
        StringBuilder sql = new StringBuilder();
        sql.append("-- Generated by perf/tools/SeedPerfRealm.java — perf fixture, NOT a migration.\n");
        sql.append("BEGIN;\n\n");

        // signing_key and oauth_client both carry FORCE ROW LEVEL SECURITY, so even this seed
        // must bind a tenant before the WITH CHECK policy will accept the row.
        sql.append("SELECT set_config('app.tenant_id', ").append(quote(tenant.toString()))
                .append(", false);\n\n");

        sql.append("INSERT INTO signing_key (\n")
                .append("    id, tenant_id, kid, algorithm, state, public_jwk, created_at,\n")
                .append("    private_key_enc, private_key_nonce, dek_wrapped, key_use, issuer, activated_at\n")
                .append(") VALUES (\n")
                .append("    ").append(quote(signingKeyRowId.toString())).append(",\n")
                .append("    ").append(quote(tenant.toString())).append(",\n")
                .append("    ").append(quote(kid)).append(",\n")
                .append("    'EdDSA',\n")
                .append("    'ACTIVE',\n")
                .append("    ").append(quote(publicJwk)).append(",\n")
                .append("    now(),\n")
                .append("    ").append(bytea(ciphertext)).append(",\n")
                .append("    ").append(bytea(nonce)).append(",\n")
                .append("    ").append(bytea(wrappedDek)).append(",\n")
                .append("    'sig',\n")
                .append("    ").append(quote(issuer)).append(",\n")
                .append("    now()\n")
                .append(");\n\n");

        // A PUBLIC client: PKCE-only, no secret, so the load driver never pays an Argon2id
        // verification per login — the credential path is a different experiment.
        sql.append("INSERT INTO oauth_client (\n")
                .append("    id, tenant_id, baseline_id, client_key, client_type, auth_method,\n")
                .append("    allowed_grants, created_at, redirect_uris\n")
                .append(") VALUES (\n")
                .append("    ").append(quote(clientRowId.toString())).append(",\n")
                .append("    ").append(quote(tenant.toString())).append(",\n")
                .append("    ").append(quote(ZERO_BASELINE.toString())).append(",\n")
                .append("    ").append(quote(clientKey)).append(",\n")
                .append("    'PUBLIC',\n")
                .append("    NULL,\n")
                .append("    'authorization_code,refresh_token',\n")
                .append("    now(),\n")
                .append("    ").append(quote(redirectUri)).append("\n")
                .append(");\n\n");

        sql.append("COMMIT;\n");

        System.out.print(sql);

        // The facts the driver needs, on stderr so stdout stays pure SQL for the psql pipe.
        System.err.println("TENANT_ID=" + tenant);
        System.err.println("BASELINE_ID=" + ZERO_BASELINE);
        System.err.println("CLIENT_ID=" + clientKey);
        System.err.println("REDIRECT_URI=" + redirectUri);
        System.err.println("SIGNING_KID=" + kid);
    }

    // ------------------------------------------------------------------ envelope crypto

    /** Mirrors EnvelopeCipher.wrapDek: wrap nonce is prefixed so unwrap is self-contained. */
    private static byte[] wrapDek(byte[] masterKeyBytes, SecretKey dek) throws Exception {
        SecretKey masterKey = new SecretKeySpec(masterKeyBytes, "AES");
        byte[] wrapNonce = randomNonce();
        byte[] wrapped = gcm(Cipher.ENCRYPT_MODE, masterKey, wrapNonce, dek.getEncoded());
        byte[] out = new byte[GCM_NONCE_BYTES + wrapped.length];
        System.arraycopy(wrapNonce, 0, out, 0, GCM_NONCE_BYTES);
        System.arraycopy(wrapped, 0, out, GCM_NONCE_BYTES, wrapped.length);
        return out;
    }

    private static byte[] gcm(int mode, SecretKey key, byte[] nonce, byte[] input)
            throws Exception {
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(mode, key, new GCMParameterSpec(GCM_TAG_BITS, nonce));
        return cipher.doFinal(input);
    }

    private static SecretKey newDek() throws Exception {
        KeyGenerator generator = KeyGenerator.getInstance("AES");
        generator.init(256, RANDOM);
        return generator.generateKey();
    }

    private static byte[] randomNonce() {
        byte[] nonce = new byte[GCM_NONCE_BYTES];
        RANDOM.nextBytes(nonce);
        return nonce;
    }

    /**
     * The 32-byte little-endian Ed25519 public key (RFC 8032 §3.1): the Y coordinate with
     * the sign of X folded into the most-significant bit. Mirrors Ed25519Keys.rawPublicKey.
     */
    private static byte[] rawPublicKey(EdECPublicKey key) {
        byte[] little = toLittleEndian(key.getPoint().getY(), 32);
        if (key.getPoint().isXOdd()) {
            little[31] |= (byte) 0x80;
        }
        return little;
    }

    private static byte[] toLittleEndian(BigInteger value, int length) {
        byte[] big = value.toByteArray();
        byte[] little = new byte[length];
        for (int i = 0; i < big.length && i < length; i++) {
            little[i] = big[big.length - 1 - i];
        }
        return little;
    }

    // ------------------------------------------------------------------ SQL helpers

    private static String bytea(byte[] value) {
        return "decode('" + HEX.formatHex(value) + "', 'hex')";
    }

    private static String quote(String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    private static String base64Url(byte[] value) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(value);
    }

    /** A stable-looking but random perf tenant; overridable so a run can be reproduced. */
    private static String newTenant() {
        return UUID.randomUUID().toString();
    }

    private static Map<String, String> parseArgs(String[] args) {
        Map<String, String> opts = new LinkedHashMap<>();
        for (int i = 0; i < args.length; i++) {
            String arg = args[i];
            if (!arg.startsWith("--")) {
                throw new IllegalArgumentException("Unexpected argument: " + arg);
            }
            if (i + 1 >= args.length) {
                throw new IllegalArgumentException("Missing value for " + arg);
            }
            opts.put(arg.substring(2), args[++i]);
        }
        return opts;
    }

    private static String required(Map<String, String> opts, String name) {
        String value = opts.get(name);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("--" + name + " is required");
        }
        return value;
    }

    private SeedPerfRealm() {
    }
}
